//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT_FFXIV_Kapture.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT_FFXIV_Kapture.Resource.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Zone.
        /// </summary>
        public static string AddZone {
            get {
                return ResourceManager.GetString("AddZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filters.
        /// </summary>
        public static string AdvancedFilters {
            get {
                return ResourceManager.GetString("AdvancedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alliance.
        /// </summary>
        public static string Alliance {
            get {
                return ResourceManager.GetString("Alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle Log.
        /// </summary>
        public static string BattleLog {
            get {
                return ResourceManager.GetString("BattleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for beta versions.
        /// </summary>
        public static string CheckForBeta {
            get {
                return ResourceManager.GetString("CheckForBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Items.
        /// </summary>
        public static string CommonItems {
            get {
                return ResourceManager.GetString("CommonItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom JSON.
        /// </summary>
        public static string CustomJSON {
            get {
                return ResourceManager.GetString("CustomJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string Discord {
            get {
                return ResourceManager.GetString("Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord enabled.
        /// </summary>
        public static string DiscordEnabled {
            get {
                return ResourceManager.GetString("DiscordEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string Endpoint {
            get {
                return ResourceManager.GetString("Endpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Common Items.
        /// </summary>
        public static string ExcludeCommonItems {
            get {
                return ResourceManager.GetString("ExcludeCommonItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Items.
        /// </summary>
        public static string ExcludeItems {
            get {
                return ResourceManager.GetString("ExcludeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude zones.
        /// </summary>
        public static string ExcludeZones {
            get {
                return ResourceManager.GetString("ExcludeZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by items.
        /// </summary>
        public static string FilterByItems {
            get {
                return ResourceManager.GetString("FilterByItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by zones.
        /// </summary>
        public static string FilterByZones {
            get {
                return ResourceManager.GetString("FilterByZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get market board data.
        /// </summary>
        public static string GetMarketBoardData {
            get {
                return ResourceManager.GetString("GetMarketBoardData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-end Duty.
        /// </summary>
        public static string HighEndDuty {
            get {
                return ResourceManager.GetString("HighEndDuty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-End Duty Only.
        /// </summary>
        public static string HighEndDutyOnly {
            get {
                return ResourceManager.GetString("HighEndDutyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        public static string HTTP {
            get {
                return ResourceManager.GetString("HTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP enabled.
        /// </summary>
        public static string HTTPEnabled {
            get {
                return ResourceManager.GetString("HTTPEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include items.
        /// </summary>
        public static string IncludeItems {
            get {
                return ResourceManager.GetString("IncludeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Mounts Only.
        /// </summary>
        public static string IncludeMounts {
            get {
                return ResourceManager.GetString("IncludeMounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include zones.
        /// </summary>
        public static string IncludeZones {
            get {
                return ResourceManager.GetString("IncludeZones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item added.
        /// </summary>
        public static string ItemAdded {
            get {
                return ResourceManager.GetString("ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item cast lot.
        /// </summary>
        public static string ItemCastLot {
            get {
                return ResourceManager.GetString("ItemCastLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item lost.
        /// </summary>
        public static string ItemLost {
            get {
                return ResourceManager.GetString("ItemLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item obtained.
        /// </summary>
        public static string ItemObtained {
            get {
                return ResourceManager.GetString("ItemObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item rolled on.
        /// </summary>
        public static string ItemRolled {
            get {
                return ResourceManager.GetString("ItemRolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item searched.
        /// </summary>
        public static string ItemSearched {
            get {
                return ResourceManager.GetString("ItemSearched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalilistic.
        /// </summary>
        public static string Kalilistic {
            get {
                return ResourceManager.GetString("Kalilistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapture Loot Tracker.
        /// </summary>
        public static string KaptureLootTracker {
            get {
                return ResourceManager.GetString("KaptureLootTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file cleared..
        /// </summary>
        public static string LogCleared {
            get {
                return ResourceManager.GetString("LogCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        public static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Format.
        /// </summary>
        public static string LogFormat {
            get {
                return ResourceManager.GetString("LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging enabled.
        /// </summary>
        public static string LoggingEnabled {
            get {
                return ResourceManager.GetString("LoggingEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log imports enabled.
        /// </summary>
        public static string LogImportsEnabled {
            get {
                return ResourceManager.GetString("LogImportsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Location.
        /// </summary>
        public static string LogLocation {
            get {
                return ResourceManager.GetString("LogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Log.
        /// </summary>
        public static string MessageLog {
            get {
                return ResourceManager.GetString("MessageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIT.
        /// </summary>
        public static string MIT {
            get {
                return ResourceManager.GetString("MIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin enabled.
        /// </summary>
        public static string PluginEnabled {
            get {
                return ResourceManager.GetString("PluginEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the latest version of the Kapture plugin..
        /// </summary>
        public static string PluginHaveLatest {
            get {
                return ResourceManager.GetString("PluginHaveLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapture plugin updated successfully. Please restart ACT now..
        /// </summary>
        public static string PluginNeedRestart {
            get {
                return ResourceManager.GetString("PluginNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update for Kapture plugin available. Do you want to download it now?.
        /// </summary>
        public static string PluginUpdateAvailable {
            get {
                return ResourceManager.GetString("PluginUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download update. Please try again later or check GitHub..
        /// </summary>
        public static string PluginUpdateFailed {
            get {
                return ResourceManager.GetString("PluginUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They obtained an item.
        /// </summary>
        public static string TheyObtain {
            get {
                return ResourceManager.GetString("TheyObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They rolled on an item.
        /// </summary>
        public static string TheyRoll {
            get {
                return ResourceManager.GetString("TheyRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Plugin Log.
        /// </summary>
        public static string ViewPluginLog {
            get {
                return ResourceManager.GetString("ViewPluginLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webhook URL.
        /// </summary>
        public static string WebhookURL {
            get {
                return ResourceManager.GetString("WebhookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You obtained an item.
        /// </summary>
        public static string YouObtain {
            get {
                return ResourceManager.GetString("YouObtain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You rolled on an item.
        /// </summary>
        public static string YouRoll {
            get {
                return ResourceManager.GetString("YouRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Zones {
            get {
                return ResourceManager.GetString("Zones", resourceCulture);
            }
        }
    }
}
