//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT_FFXIV.Aetherbridge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT_FFXIV.Aetherbridge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0300adventurerADVaventurierAVNAbenteurerABEすっぴん士ADV
        ///1301gladiatorGLAgladiateurGLAGladiatorGLA剣術士GLA
        ///2302pugilistPGLpugilistePGLFaustkämpferFST格闘士PGL
        ///3301marauderMRDmaraudeurMRDMarodeurMAR斧術士MRD
        ///4302lancerLNCmaître d&apos;hastHASPikenierPIK槍術士LNC
        ///5303archerARCarcherARCWaldläuferWDL弓術士ARC
        ///6314conjurerCNJélémentalisteÉLMDruideDRU幻術士CNJ
        ///7313thaumaturgeTHMoccultisteOCCThaumaturgTHM呪術士THM
        ///8330carpenterCRPmenuisierMENZimmerer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ClassJob {
            get {
                return ResourceManager.GetString("ClassJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1169Falsethe Thousand Maws of Toto–Rakles Mille Gueules de Toto-RakTausend Löcher von Toto-Rak監獄廃墟 トトラクの千獄
        ///2164Falsethe Tam–Tara Deepcroftl&apos;Hypogée de Tam-TaraTotenacker Tam-Tara地下霊殿 タムタラの墓所
        ///3161FalseCopperbell Minesles Mines de ClochecuivreKupferglocken-Mine封鎖坑道 カッパーベル銅山
        ///4157FalseSastashaSastashaSastasha天然要害 サスタシャ浸食洞
        ///5172Falsethe Aurum Valele Val d&apos;AurumGoldklamm霧中行軍 オーラムヴェイル
        ///6166FalseHaukke Manorle Manoir des HaukkeHaukke-Herrenhaus名門屋敷 ハウケタ御用邸
        ///7162FalseHalatal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ContentFinderCondition {
            get {
                return ResourceManager.GetString("ContentFinderCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 135740luminous water crystalluminous water crystalsLuminous Water Crystalluminous water crystalluminous water crystalscristal lumineux d&apos;eaucristaux lumineux d&apos;eauCristal lumineux d&apos;eaucristal lumineux d&apos;eaucristaux lumineux d&apos;eaustrahlend[a] Wasserkristallstrahlend[a] WasserkristalleStrahlender Wasserkristallstrahlendstrahlend^strahlend(?:e|er|es|en)? Wasserkristall$^strahlend(?:e|er|es|en)? Wasserkristalle$発光性ウォータークリスタル発光性ウォータークリスタル発光性ウォータークリスタルTrueFalse
        ///135730luminous li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00
        ///1847
        ///2847
        ///3847
        ///4847
        ///5847
        ///6848
        ///7848
        ///8848
        ///9848
        ///10848
        ///11849
        ///12849
        ///13849
        ///141055
        ///15842
        ///16842
        ///17842
        ///18842
        ///19842
        ///20842
        ///21841
        ///22841
        ///23841
        ///24846
        ///25841
        ///26841
        ///27841
        ///28841
        ///29841
        ///30841
        ///31841
        ///32841
        ///33841
        ///34841
        ///35841
        ///36841
        ///37841
        ///38841
        ///39841
        ///40841
        ///411053
        ///421053
        ///431053
        ///441053
        ///45816
        ///46816
        ///47816
        ///48816
        ///49850
        ///501054
        ///511767
        ///52843
        ///53844
        ///54845
        ///55844
        ///56844
        ///57845
        ///58844
        ///59844
        ///60845
        ///61845
        ///62845
        ///63844
        ///6484 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ItemAction {
            get {
                return ResourceManager.GetString("ItemAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1Englishen
        ///2Frenchfr
        ///3Germande
        ///4Japaneseja
        ///5Chinesecn
        ///6Koreankr
        ///.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000
        ///101
        ///20132
        ///30133
        ///40148
        ///50152
        ///60153
        ///70154
        ///80164
        ///90169
        ///100728
        ///110128
        ///120129
        ///130130
        ///14373131
        ///150134
        ///160135
        ///170137
        ///180138
        ///190139
        ///200140
        ///210141
        ///220145
        ///230146
        ///240147
        ///250156
        ///260177
        ///270178
        ///280179
        ///29022
        ///300180
        ///310157
        ///320159
        ///330206
        ///34849161
        ///350202
        ///360207
        ///370168
        ///380172
        ///390208
        ///40850161
        ///41372161
        ///42854163
        ///43855163
        ///44856163
        ///450158
        ///460162
        ///470217
        ///48599166
        ///49873167
        ///5092217 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18LevemeteMandatFreibriefギルドリーヴ
        ///20HydaelynHydaelynHydaelynハイデリン
        ///21EorzeaÉorzéaEorzeaエオルゼア
        ///22La NosceaNosceaLa Nosceaラノシア
        ///23The Black ShroudForêt de SombrelinceulFinsterwald黒衣森
        ///24ThanalanThanalanThanalanザナラーン
        ///25CoerthasCoerthasCoerthasクルザス
        ///26Mor DhonaMor DhonaMor Dhonaモードゥナ
        ///27Limsa LominsaLimsa LominsaLimsa Lominsaリムサ・ロミンサ
        ///28Limsa Lominsa Upper DecksLimsa Lominsa - Le TillacObere Decksリムサ・ロミンサ：上甲板層
        ///29Limsa Lominsa Lower DecksLimsa Lominsa - L&apos;EntrepontUnte [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PlaceName {
            get {
                return ResourceManager.GetString("PlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10000
        ///20000
        ///30000
        ///40000
        ///50000
        ///60000
        ///70000
        ///80000
        ///90000
        ///100000
        ///110000
        ///130000
        ///140000
        ///150000
        ///160000
        ///170000
        ///180000
        ///190000
        ///200000
        ///210000
        ///220000
        ///240000
        ///250000
        ///260000
        ///270000
        ///280000
        ///290000
        ///128225002811
        ///129225002912
        ///130245044013
        ///131245044114
        ///13223506522
        ///13323506533
        ///134225023015
        ///135225023116
        ///1362250242572
        ///137225023217
        ///138225023318
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TerritoryType {
            get {
                return ResourceManager.GetString("TerritoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23Asura
        ///24Belias
        ///25Chaos
        ///26Hecatoncheir
        ///27Moomba
        ///28Pandaemonium
        ///29Shinryu
        ///30Unicorn
        ///31Yojimbo
        ///32Zeromus
        ///33Twintania
        ///34Brynhildr
        ///35Famfrit
        ///36Lich
        ///37Mateus
        ///38Shemhazai
        ///39Omega
        ///40Jenova
        ///41Zalera
        ///42Zodiark
        ///43Alexander
        ///44Anima
        ///45Carbuncle
        ///46Fenrir
        ///47Hades
        ///48Ixion
        ///49Kujata
        ///50Typhon
        ///51Ultima
        ///52Valefor
        ///53Exodus
        ///54Faerie
        ///55Lamia
        ///56Phoenix
        ///57Siren
        ///58Garuda
        ///59Ifrit
        ///60Ramuh
        ///61Titan
        ///62Diabolos
        ///63Gilgamesh
        ///64Leviathan
        ///65Midgardsormr
        ///66 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
    }
}
