//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT_FFXIV.Aetherbridge.Mocks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACT_FFXIV.Aetherbridge.Mocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Fri, 29 Nov 2019 20:43:56 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 34
        ///X-RateLimit-Reset: 1575063604
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;c654f374d1aa53d86e542523709b4b17&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scope [rest of string was truncated]&quot;;.
        /// </summary>
        public static string assets_headers_200 {
            get {
                return ResourceManager.GetString("assets_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/assets/16366858&quot;,&quot;id&quot;:16366858,&quot;node_id&quot;:&quot;MDEyOlJlbGVhc2VBc3NldDE2MzY2ODU4&quot;,&quot;name&quot;:&quot;TestLibrary.dll&quot;,&quot;label&quot;:&quot;&quot;,&quot;uploader&quot;:{&quot;login&quot;:&quot;kalilistic&quot;,&quot;id&quot;:35899782,&quot;node_id&quot;:&quot;MDQ6VXNlcjM1ODk5Nzgy&quot;,&quot;avatar_url&quot;:&quot;https://avatars1.githubusercontent.com/u/35899782?v=4&quot;,&quot;gravatar_id&quot;:&quot;&quot;,&quot;url&quot;:&quot;https://api.github.com/users/kalilistic&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic&quot;,&quot;followers_url&quot;:&quot;https://api.github.com/users/kalilistic/followers&quot;,&quot;foll [rest of string was truncated]&quot;;.
        /// </summary>
        public static string assets_response_200 {
            get {
                return ResourceManager.GetString("assets_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:54:42 GMT
        ///Content-Length: 2
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 52
        ///X-RateLimit-Reset: 1574905933
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: &quot;98f0c1b396a4e5d54f4d5fe561d54b44&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=5&gt;; rel=&quot;prev&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=5&gt;; rel=&quot;last&quot;, &lt;https://api.github.com/reposi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string empty_headers_200 {
            get {
                return ResourceManager.GetString("empty_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        public static string empty_response_200 {
            get {
                return ResourceManager.GetString("empty_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 690856TrueEden&apos;s Gate: Sepulture (Savage)L&apos;Éveil d&apos;Éden - Inhumation (sadique)Edens Erwachen - Beerdigung (episch)希望の園エデン零式：覚醒編4.
        /// </summary>
        public static string GameDataMock {
            get {
                return ResourceManager.GetString("GameDataMock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 01:19:18 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 59
        ///X-RateLimit-Reset: 1574907558
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;88e20fbc23b7b93cb30435f580f9f43a&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scope [rest of string was truncated]&quot;;.
        /// </summary>
        public static string get_latest_headers_200 {
            get {
                return ResourceManager.GetString("get_latest_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21698387&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21698387/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21698387/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v6.0.30%2B239&quot;,&quot;id&quot;:21698387,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxNjk4Mzg3&quot;,&quot;tag_name&quot;:&quot;v6.0.30+239&quot;,&quot;target_commitish&quot;:&quot;master&quot;,&quot;name&quot;:&quot;Version 6.0.30+239&quot;,&quot;draft&quot;:false,&quot;aut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string get_latest_response_200 {
            get {
                return ResourceManager.GetString("get_latest_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:40:35 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 55
        ///X-RateLimit-Reset: 1574905016
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;f84a0386cc559be197df720503fbfb8e&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=2&gt;; rel=&quot;next&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=5&gt;; rel=&quot;last&quot;
        ///Access-Control-Expo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page1_headers_200 {
            get {
                return ResourceManager.GetString("page1_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21716550&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21716550/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21716550/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v6.0.53&quot;,&quot;id&quot;:21716550,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxNzE2NTUw&quot;,&quot;tag_name&quot;:&quot;v6.0.53&quot;,&quot;target_commitish&quot;:&quot;master&quot;,&quot;name&quot;:&quot;Version 6.0.53&quot;,&quot;draft&quot;:false,&quot;author&quot;:{&quot;login&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page1_response_200 {
            get {
                return ResourceManager.GetString("page1_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:48:21 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 53
        ///X-RateLimit-Reset: 1574905016
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;0c9a5951ca33c0afe5d94e7e57329765&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=1&gt;; rel=&quot;prev&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=3&gt;; rel=&quot;next&quot;, &lt;https://api.github [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page2_headers_200 {
            get {
                return ResourceManager.GetString("page2_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21606310&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21606310/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21606310/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v6.0.12-219&quot;,&quot;id&quot;:21606310,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxNjA2MzEw&quot;,&quot;tag_name&quot;:&quot;v6.0.12-219&quot;,&quot;target_commitish&quot;:&quot;master&quot;,&quot;name&quot;:&quot;Version 6.0.12-219&quot;,&quot;draft&quot;:false,&quot;auth [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page2_response_200 {
            get {
                return ResourceManager.GetString("page2_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:50:59 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 59
        ///X-RateLimit-Reset: 1574905859
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;3df2326a89adefd0f9285991c9281d00&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=2&gt;; rel=&quot;prev&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=4&gt;; rel=&quot;next&quot;, &lt;https://api.github [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page3_headers_200 {
            get {
                return ResourceManager.GetString("page3_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21540173&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21540173/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21540173/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v5.0.11&quot;,&quot;id&quot;:21540173,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxNTQwMTcz&quot;,&quot;tag_name&quot;:&quot;v5.0.11&quot;,&quot;target_commitish&quot;:&quot;master&quot;,&quot;name&quot;:&quot;Version 5.0.11&quot;,&quot;draft&quot;:false,&quot;author&quot;:{&quot;login&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page3_response_200 {
            get {
                return ResourceManager.GetString("page3_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:52:13 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 58
        ///X-RateLimit-Reset: 1574905933
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;51749c9a678265d828632507f5f8bcb1&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=3&gt;; rel=&quot;prev&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=5&gt;; rel=&quot;next&quot;, &lt;https://api.github [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page4_headers_200 {
            get {
                return ResourceManager.GetString("page4_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21530826&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21530826/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21530826/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v3.1.17&quot;,&quot;id&quot;:21530826,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxNTMwODI2&quot;,&quot;tag_name&quot;:&quot;v3.1.17&quot;,&quot;target_commitish&quot;:&quot;master&quot;,&quot;name&quot;:&quot;Version 3.1.17&quot;,&quot;draft&quot;:false,&quot;author&quot;:{&quot;login&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page4_response_200 {
            get {
                return ResourceManager.GetString("page4_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:54:01 GMT
        ///Transfer-Encoding: chunked
        ///Status: 200 OK
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 53
        ///X-RateLimit-Reset: 1574905933
        ///Cache-Control: public, max-age=60, s-maxage=60
        ///Vary: Accept
        ///ETag: W/&quot;425ae1f1d5779f47b905d33fc66dbff7&quot;
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Link: &lt;https://api.github.com/repositories/220696219/releases?page=4&gt;; rel=&quot;prev&quot;, &lt;https://api.github.com/repositories/220696219/releases?page=1&gt;; rel=&quot;first&quot;
        ///Access-Control-Exp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page5_headers_200 {
            get {
                return ResourceManager.GetString("page5_headers_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21344228&quot;,&quot;assets_url&quot;:&quot;https://api.github.com/repos/kalilistic/TestLibrary/releases/21344228/assets&quot;,&quot;upload_url&quot;:&quot;https://uploads.github.com/repos/kalilistic/TestLibrary/releases/21344228/assets{?name,label}&quot;,&quot;html_url&quot;:&quot;https://github.com/kalilistic/TestLibrary/releases/tag/v1.0.21&quot;,&quot;id&quot;:21344228,&quot;node_id&quot;:&quot;MDc6UmVsZWFzZTIxMzQ0MjI4&quot;,&quot;tag_name&quot;:&quot;v1.0.21&quot;,&quot;target_commitish&quot;:&quot;f58e7dc6af31b1519606f72b56bd3b45595b703b&quot;,&quot;name&quot;:&quot;myproduct-v1. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string page5_response_200 {
            get {
                return ResourceManager.GetString("page5_response_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 01:10:49 GMT
        ///Transfer-Encoding: chunked
        ///Status: 403 Forbidden
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 0
        ///X-RateLimit-Reset: 1574906304
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
        ///Access-Control-Allow-Origin: *
        ///Strict-Transport-Security:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rate_limit_headers_403 {
            get {
                return ResourceManager.GetString("rate_limit_headers_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;API rate limit exceeded for 192.0.2.255. (But here&apos;s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)&quot;,&quot;documentation_url&quot;:&quot;https://developer.github.com/v3/#rate-limiting&quot;}.
        /// </summary>
        public static string rate_limit_response_403 {
            get {
                return ResourceManager.GetString("rate_limit_response_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server: GitHub.com
        ///Date: Thu, 28 Nov 2019 00:58:24 GMT
        ///Transfer-Encoding: chunked
        ///Status: 404 Not Found
        ///X-RateLimit-Limit: 60
        ///X-RateLimit-Remaining: 59
        ///X-RateLimit-Reset: 1574906304
        ///X-GitHub-Media-Type: github.v3; format=json
        ///Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type
        ///Access-Control-Allow-Origin: *
        ///Strict-Transport-Security: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string repo_not_found_headers_404 {
            get {
                return ResourceManager.GetString("repo_not_found_headers_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;message&quot;:&quot;Not Found&quot;,&quot;documentation_url&quot;:&quot;https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository&quot;}.
        /// </summary>
        public static string repo_not_found_response_404 {
            get {
                return ResourceManager.GetString("repo_not_found_response_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;itemID&quot;: 27958,
        ///    &quot;lastUploadTime&quot;: 1594492318137,
        ///    &quot;listings&quot;: [
        ///        {
        ///            &quot;creatorID&quot;: &quot;e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&quot;,
        ///            &quot;lastReviewTime&quot;: 53996,
        ///            &quot;listingID&quot;: &quot;3797ccfb02a4957b001b791e8784f688575ff66853e280b17e06238128e15341&quot;,
        ///            &quot;pricePerUnit&quot;: 1050,
        ///            &quot;quantity&quot;: 1,
        ///            &quot;retainerID&quot;: &quot;3fb0790797fdd985e4e7c2395fda1986346b7e0f7d183926ad04fa7ddd09b79a&quot;,
        ///            &quot;sellerID&quot;: &quot;489f08b881 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string universalis_response_bad_request {
            get {
                return ResourceManager.GetString("universalis_response_bad_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;itemID&quot;: 27958,
        ///    &quot;lastUploadTime&quot;: 1594492318137,
        ///    &quot;listings&quot;: [
        ///        {
        ///            &quot;creatorID&quot;: &quot;e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&quot;,
        ///            &quot;lastReviewTime&quot;: 53996,
        ///            &quot;listingID&quot;: &quot;3797ccfb02a4957b001b791e8784f688575ff66853e280b17e06238128e15341&quot;,
        ///            &quot;pricePerUnit&quot;: 1050,
        ///            &quot;quantity&quot;: 1,
        ///            &quot;retainerID&quot;: &quot;3fb0790797fdd985e4e7c2395fda1986346b7e0f7d183926ad04fa7ddd09b79a&quot;,
        ///            &quot;sellerID&quot;: &quot;489f08b881 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string universalis_response_success {
            get {
                return ResourceManager.GetString("universalis_response_success", resourceCulture);
            }
        }
    }
}
